version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: http://localhost:3000
      MONGO_URL: mongodb://mongo:27017/meteor

  mongo:
    image: mongo:latest
    volumes:
      - type: volume
        target: /data/db
volumes:
  mongodb: