version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: http://localhost
      # MONGO_URL: mongodb+srv://admin:password_barkcluster@barkcluster.1jdxh2j.mongodb.net/?retryWrites=true&w=majority\
      PORT: 3000

  mongo:
    image: mongo:latest
    volumes:
      - type: volume
        target: /data/db
volumes:
  mongodb: